language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - 'node'
git:
  depth: 3
scripts:
  - yarn test
notifications:
  slack: 
    secure: "YrF+2xGwOROZK/39hUxrlfCPJKdg0nnPN326txKRbgiMyLxjglxhubC1tFPKyFcNgAFel0g6ubRLKtLby/TkF1Ouuw41fbKh590685C0auP9uo2YcqGrEy5tanY2OD7GRMRFV5a5cecLhxsoqiylm0AhbT0iAJcaRT+2z0hoxk+li0xbzRFp8FIiri8YnaCLooKPzz5ssnil9wi1k/z7OAeE3P2L7MR8B3a7e0gHekF0290i1O66Nj5LMSe2Yp/GOmaa9CHWLFBCU3lFI3mfgoAQE3D5sXV0pWfaxQZBbKSGR6VwxuwY+5HbktBywYbwxqsHOXdI6Lnv3rxzdT584eEqP+7fI6kdhBkCEUSnqxPwX0amgu0lGZ4eVqOEDAbv0hzfX5SM0j5tvmANpgYpaEribVQrSNyT2WKLRluTGgLRPzNo27tIUM04hyVRu8tn42HcpjsDwTu5JZX8HbZ2rPWRa7xBePy5RYzIYbC2JLtQ0lFONkMsjhRQsZlYAZyJe5HGxFmM3lhrPIQds92aAxh8SNuqOrclpxd6nrOiT/q1u4ZMqaqWR2SXt7qQIFyQVEaH/bfw47eve9d9jzuY3T8H6pxvYG9QVKtyzJawFT1KyoX9+vnhSL2i5J7y2HSlcVj7z+k+Y5j/xkN11Qj1hht7Pj1yVGB4HttRcy3Tcwg="

  email:
    recipients:
      - jedave.co@gmail.com
      - 15-10345@usb.ve
deploy:
  provider: heroku
  skip-cleanup : true
  keep-history: true
  api_key:
    secure: "e2/d4K2dIt9ojn3aaDeKmz+W4Y4oBx006WaPk7b7uTCW3M6EWZahuJJ2cVneRnh+oC1TLg3LpFqT+aMZO9GOS8cEHJ0X5rne1y01eiwujSL9dvwtIZBb/mRtV1esJSHvszIHSGipiPoi9WMZI/Yh7bdHapXadAu7Fu/1pBn1xKnfBfHdQb4+7X/iXl32roppn4fo9kUWjern4x/CDaXUzCvFaP6R5kiaWwh1DEEJ7SG42kDgayxkIUdCcvGj1MzQ1hNGaME8Lz8EdN6H9Xtm492HskWQ9DJsb1yeJDOzWMAYQtyhupnO1ZD+O5x6Oefp92anvWEMNS3sjOJ5/jB8EhWaebrLhveU20oqU07O5sjNDC2fGJZ8zPBCXCUSLlgcSP2bgUegGZMg/+dmgwOMhs6AFXN3yhfoZDELTkdkVuUd+EiKFXhoOtysVX7yyRnfZKlzMqv/DJcivVne7TArFThT+jCHMTOTMNSVm+SvyzO3sWRmSUni5gDtAfx1BP0xQtkpog0W2xqHyDJ1NX1t/aWKWXV9LugggR7GVRl+QzZuhdMgAzVX8H9EIXFBmATHaJjpXZ7o0IjBKB2o/40QZCkP8NHcV003L50GRwyFA4ff7Z/pVitm7j7lSwu6JeW4GmPNWNhcLqzT/5ekctPDdxcE4A1/SzQd3n7XbzpArfk="
  app: platzi-store-backend-travisci
  on:
    repo: jesusdavc/platzi-store-backend
